apiVersion: v1
kind: Service
metadata:
  name: nginx-service-config
spec:
  type: NodePort          
  ports:
    - port: 8080           # The port your service will be exposed on inside the cluster
      targetPort: 80       # The port your container is listening on
      nodePort: 30002      # Specify the NodePort between 30000-32767
  selector:
    service: nginx-service           # Match the label defined in the pod's metadata
