apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP          # Explicitly specify the service type
  ports:
    - port: 8080           # Port which service listens on and forwards the traffic to pod on port 80
      targetPort: 80       # The port listened to by the pod
  selector:
    service: backend
